Changed data format
Bakizavr/GeoInfo pull request #1
Opened 2023-05-08 14:45 UTC by Bakizavr

2023-05-08 17:54 UTC, flor3sc0 requested changes

2023-05-08 17:54 UTC, flor3sc0 commented on Service/CityService.cs
>              return createCity.Id;
Id должно генерироваться при создании, а не приниматься из запроса

2023-05-08 17:54 UTC, flor3sc0 commented on Service/CityService.cs
> +using System.Diagnostics;
удаляй лишние юзинги

2023-05-08 17:54 UTC, flor3sc0 commented on Models/City.cs
> +    //public static void Update(long Id, string Name, string AsciiName, string AlternateName, string Latitude, string Longitude, string FeatureClass, string FeatureCode, string CountryCode, string Cc
закомментированный код либо должен быть описать с помощью TODO, либо удален

2023-05-08 17:54 UTC, flor3sc0 commented on Service/DataBaseInitializator.cs
>              Admin2Code = subs[11],
убери вот эти все AdminСode, слишком много полей

2023-05-08 17:54 UTC, flor3sc0 commented on Models/Dto/UpdateCity.cs
переименовать в UpdateCityDto. Тоже самое с Create

2023-05-08 17:54 UTC, flor3sc0 commented on Service/CityService.cs
> +            var city = City.Create(createCity.Id, createCity.Name, createCity.AsciiName, createCity.AlternateName, createCity.Latitude, createCity.Longitude, createCity.FeatureClass, createCity.Featu
createCity.ModificationDate не нужно принимать из запроса

2023-05-08 17:54 UTC, flor3sc0 commented on Models/City.cs
> +    public decimal Latitude { get; set; }
если изменились типы, значит нужно изменить их и в БД.
Два способа:
- Т.к данные тестовые, и миграция первая, можно: удалить таблицу из бд, удалить папку с миграциями и просто пересоздать все.
- или сделать еще одну миграцию, для того что бы поменять структуру в БД

2023-05-08 17:56 UTC, flor3sc0 commented
[Feature](https://github.com/Bakizavr/GeoInfo/tree/Feature) не совсем удачное название для ветки, оно слишком общее, лучше подошло бы что-то вроде `change_data_types`

2023-05-08 18:13 UTC, flor3sc0 commented on Models/City.cs
> +    public static City Create(long Id, string Name, string AsciiName, string AlternateName, decimal Latitude, decimal Longitude, string FeatureClass, string FeatureCode, string CountryCode, string Cc
Все поля с маленькой буквы

2023-05-11 06:42 UTC, flor3sc0 commented on Program.cs
> +AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
зачем это? просто удали старую миграцию и создай новую

2023-05-11 06:43 UTC, flor3sc0 commented on RU.txt
положи этот файл в папку что-то типо `InputFiles`

и переименуй его, что бы он описывал содержимое

2023-05-11 06:44 UTC, Bakizavr commented on Program.cs
> +AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
Без этого не работает занесение даты в БД

2023-05-11 06:44 UTC, flor3sc0 commented on Models/Dto/UpdateCityDto.cs
> +        public int Id { get; set; }
в методе передается отдельно Id

2023-05-11 06:46 UTC, flor3sc0 commented on Service/CityService.cs
> +        public async Task<long> CreateCityAsync(CreateCityDto createCity)
переменные тоже нужно переименовать

2023-05-11 06:49 UTC, flor3sc0 commented on Program.cs
> +AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
так ты типы изменил, а миграция то где? у тебя в бд везде строки

2023-05-15 11:38 UTC, flor3sc0 commented on Service/CityService.cs
> +            var city = City.Create(establishedCity.Name, establishedCity.AsciiName, establishedCity.AlternateName, establishedCity.Latitude, establishedCity.Longitude, establishedCity.FeatureClass, e
если полей много, лучше каждое из них писать с новой строки, так будет гораздо читабельнее

2023-05-15 11:45 UTC, flor3sc0 commented on DockerInit.txt
> +docker run -d --name some-postgres -e
дай образу более понятно название, и это должно быть все в одну строку

2023-05-15 15:35 UTC, Bakizavr commented on DockerInit.txt
> +docker run -d --name some-postgres -e
я пока не совсем понимаю, что происходит в этом файле

2023-05-16 07:17 UTC, flor3sc0 approved these changes

2023-05-16 07:37 UTC, merged