RegistreServices and TwoCities
Bakizavr/GeoInfo pull request #6
Opened 2023-05-17 11:30 UTC by Bakizavr

Service registration and method of displaying information about the two cities

2023-05-17 13:17 UTC, flor3sc0 requested changes

2023-05-17 13:17 UTC, flor3sc0 commented on Service/RegistreDataBaseExtension.cs
> +    public static class RegistreDataBaseExtension
DataBaseExtension**S**

2023-05-17 13:17 UTC, flor3sc0 commented on Service/RegistreDataBaseExtension.cs
> +            var connection = builder.Configuration.GetConnectionString("DefaultConnection");
что за `connection`? это  `connectionString`

2023-05-17 13:17 UTC, flor3sc0 commented on Service/RegistreDataBaseExtension.cs
> +        public static IServiceCollection RegistreDataBase(this IServiceCollection services, WebApplicationBuilder builder)
не нужен тут весь билдер, прокинь сюда сразу `Configuration`

2023-05-17 13:17 UTC, flor3sc0 commented on Service/ServicesExtension.cs
> +public static class ServicesExtension
ServiceCollection**S**

2023-05-17 13:17 UTC, flor3sc0 commented on Service/ServicesExtension.cs
> +    public static IServiceCollection RegistreServices(this IServiceCollection services)
`AddApplicationServices`

2023-05-17 13:17 UTC, flor3sc0 commented on Program.cs
> +/*Вместо этого "var connection = builder.Configuration.GetConnectionString("DefaultConnection");
эти комментарии тут не нужны

2023-05-17 13:17 UTC, flor3sc0 commented on Program.cs
> +services.RegistreServices();//Вместо этого "services.AddScoped<CityService>();" добавил метод расширения
тут тоже коммент лишний

2023-05-17 13:17 UTC, flor3sc0 commented on Service/CityService.cs
> +                    var _cityDict = new TimeZoneDict();
какая-то магия происходит, что за класс?

2023-05-17 13:17 UTC, flor3sc0 commented on Service/CityService.cs
> +                else { info1 = $"Город {cities[1].Name} находится севернее города {cities[0].Name}."; }
отформатируй код

2023-05-17 13:17 UTC, flor3sc0 commented on Service/CityService.cs
> +            string info1 = "";
вместо этого лучше отдельные поля в дто

и их нужно назвать соответствующе

2023-05-17 13:17 UTC, flor3sc0 commented on Service/CityService.cs
> +        public async Task<TwoCitiesInfo> GetTwoCitiesAsync(string name1, string name2)
`TwoCitiesInfo`-> `TwoCitiesInfoDto`

2023-05-17 13:17 UTC, flor3sc0 commented on Service/CityService.cs
> +                    _cityDict.Dict();
что за метод ? тут что-то слишком перемудрил

2023-05-18 07:09 UTC, Bakizavr commented on Service/CityService.cs
> +                    var _cityDict = new TimeZoneDict();
Это класс для вычисления разницы во времени, если города находятся в разных часовых поясах

2023-05-18 09:54 UTC, flor3sc0 commented on Program.cs
> +builder.Services.AddSwaggerGen(c =>
тоже в ServiceCollectionExtensions в AddSwagger

2023-05-18 15:19 UTC, flor3sc0 requested changes

2023-05-18 15:19 UTC, flor3sc0 commented on Service/CityService.cs
> +            }
это можно вынести в приватный метод и вернуть из метода например кортеж

2023-05-18 15:19 UTC, flor3sc0 commented on Service/CityService.cs
> +                if (cities[0].Latitude > cities[1].Latitude) {latitudeDifference = $"Город {cities[0].Name} находится севернее города {cities[1].Name}.";}
тут текст можно вынести в переменную, и потом использовать string.Format

2023-05-18 15:19 UTC, flor3sc0 commented on Models/TimeZoneDict.cs
> +        public Dictionary<string, int> timeZones = new Dictionary<string, int>()
- переименовать класс сделать его статическим 
- сделать этот словарь приватным
- сделать публичный статичный метод получения из словаря значения по строке

2023-05-18 15:21 UTC, flor3sc0 commented on Service/CityService.cs
> +            }
1

2023-05-20 09:14 UTC, flor3sc0 requested changes

2023-05-20 09:14 UTC, flor3sc0 commented on Controllers/CitiesController.cs
> +        this.cityService = cityService;
зачем поменял? раньше было правильно

2023-05-20 09:14 UTC, flor3sc0 commented on Service/DataBaseInitializator.cs
> +    public ApplicationDbContext applicactionDbContext;
в слове ошибка, поле должно быть приватным

2023-05-20 09:14 UTC, flor3sc0 commented on Service/CityService.cs
> +            var output = "Город {0} находится севернее города {1}.";
latitudeDifferenceTemplate

2023-05-20 09:14 UTC, flor3sc0 commented on Controllers/CitiesController.cs
> +    public async Task<ActionResult<IEnumerable<CityDto>>> GetTwoCities(string name1, string name2, CancellationToken cancellationToken)
не соответствует возвращаемому типу из метода


и почти во всех методах ProducesResponseType тоже с ошибкой

2023-05-20 09:14 UTC, flor3sc0 commented on Controllers/CitiesController.cs
> +        if (cities == null) return NotFound("Города не найдены");
проверь метод, у тебя тут никогда не будет null

2023-05-20 09:14 UTC, flor3sc0 commented on Service/CityService.cs
>              if (city != null) return;
тут что-то не так...

2023-05-20 09:14 UTC, flor3sc0 commented on Controllers/CitiesController.cs
> +        var city = await cityService.GetCityByIdAsync(id, cancellationToken);
зачем дважды делать запрос? 

вся эта логика должна быть в DeleteCityAsync

2023-05-20 09:14 UTC, flor3sc0 commented on Models/ConvertTimeZonesToDigital.cs
> +    public static class ConvertTimeZonesToDigital
это не метод который что-то делает, это название класса.
больше подходит что-то вроде TimeZonesToDigitalConverter, а для метод тогда будет просто Convert

2023-05-20 09:14 UTC, flor3sc0 commented on Models/ConvertTimeZonesToDigital.cs
> +            var timeOfCity = TimeZones[timeZone];
1. можно без переменной
2. что будет если сюда передать ключ которого нет в словаре?

2023-05-20 09:14 UTC, flor3sc0 commented on Service/CityService.cs
> +        private (string, string) GetInfoAboutLatitudeTimeDifference(List<City> cities, (string latitudeDifference, string timeDifference) latitudeAndTime)
зачем передавать сюда кортеж пустых строк? 
и потом его возвращать?

2023-07-09 06:28 UTC, flor3sc0 requested changes

2023-07-09 06:28 UTC, flor3sc0 commented on Controllers/CitiesController.cs
> +[CustomExceptionFilterAttribute]
это лишнее, глобально уже зарегано в programm через AddController

2023-07-09 06:28 UTC, flor3sc0 commented on Service/CityService.cs
> +                    : latitudeAndTime.latitude = string.Format(latitudeDifferenceTemplate, cities[1].Name, cities[0].Name);
перемудрил тут, можно проще:

`latitudeAndTime.latitude = условие ? string.Format(...) : string.Format(...)`

2023-07-09 06:28 UTC, flor3sc0 commented on Service/CityService.cs
> +                    TimeZonesToDigitalConverter.Convert(cities[0].TimeZone))} час(а).";
тут тоже самое


и вычисление разницы можно вынести в приватные метод с понятным названием

2023-07-09 06:28 UTC, flor3sc0 commented on Filters/CustomExceptionFilterAttribute.cs
> +        if (context.Exception is NotFoundException)
тут вообще ничего не происходит

2023-07-09 06:32 UTC, flor3sc0 commented on Service/CityService.cs
> +            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(cancellationToken);
AsNoTracking

2023-07-09 11:58 UTC, flor3sc0 requested changes

2023-07-09 11:58 UTC, flor3sc0 commented on Filters/CustomExceptionFilterAttribute.cs
> +    public CustomExceptionFilterAttribute(IHostEnvironment environment) =>
a namespace то где?

2023-07-09 11:58 UTC, flor3sc0 commented on Service/CityService.cs
> +            var count = await source.AsNoTracking().CountAsync(cancellationToken);
тут не нужно AsNoTracking

2023-07-09 11:58 UTC, flor3sc0 commented on Service/CityService.cs
> +        int TimeDifference(string city1, string city2)
Названия методов должны быть глаголами

2023-07-09 11:58 UTC, flor3sc0 commented on Filters/CustomExceptionFilterAttribute.cs
> +        //Log.Error(exception, "An unhandled exception has occurred");
закомментированный код либо должен быть помечен TODO, либо удален

2023-07-10 16:46 UTC, flor3sc0 approved these changes

2023-07-10 17:06 UTC, merged